apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.metadata.labels.app }}
    type: {{ .Values.metadata.labels.type }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
